name: CI_DSA

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio de código
        uses: actions/checkout@v2
      - name: Instalar JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '23'
      - name: Construir proyecto con Maven
        run: | 
          mvn clean package -DskipTests
          ls target/
      - name: Guardar JAR para despliegue
        uses: actions/upload-artifact@v4
        with:
          name: moviecards
          path: '${{ github.workspace }}/target/*.jar'

  qa:
    needs: build
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v2
      - name: Instalar JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: "23"
          distribution: "adopt"
      - name: Construir con Maven
        run: mvn clean package -DskipTests
      - name: Revisar la calidad del código con Sonarqube
        run: |
          mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=admin
